package com.brkomrs.sttopla.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "dbo.Trucks".
*/
public class TruckInfDao extends AbstractDao<TruckInf, Long> {

    public static final String TABLENAME = "dbo.Trucks";

    /**
     * Properties of entity TruckInf.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property TankNumber = new Property(1, int.class, "TankNumber", false, "TANK_NUMBER");
        public final static Property Plate = new Property(2, String.class, "Plate", false, "PLATE");
    }

    private DaoSession daoSession;


    public TruckInfDao(DaoConfig config) {
        super(config);
    }
    
    public TruckInfDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"dbo.Trucks\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: Id
                "\"TANK_NUMBER\" INTEGER NOT NULL ," + // 1: TankNumber
                "\"PLATE\" TEXT);"); // 2: Plate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"dbo.Trucks\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TruckInf entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindLong(2, entity.getTankNumber());
 
        String Plate = entity.getPlate();
        if (Plate != null) {
            stmt.bindString(3, Plate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TruckInf entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindLong(2, entity.getTankNumber());
 
        String Plate = entity.getPlate();
        if (Plate != null) {
            stmt.bindString(3, Plate);
        }
    }

    @Override
    protected final void attachEntity(TruckInf entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TruckInf readEntity(Cursor cursor, int offset) {
        TruckInf entity = new TruckInf( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.getInt(offset + 1), // TankNumber
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // Plate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TruckInf entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTankNumber(cursor.getInt(offset + 1));
        entity.setPlate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TruckInf entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TruckInf entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TruckInf entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
